name: Build, test and publish
on: [ push ]

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      generate-build-number: false
      conventional-commits-publish-conditions: false
      # Workaround for 6.0.401
      dotnet-version: 6.0.302
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}